### Importación de datos

In [24]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

"""
Descomentar las siguientes lineas si se quiere cargar los archivos desde la computadora local
"""

# url = "./base-de-datos-challenge1-latam/tienda_1.csv"
# url2 = "./base-de-datos-challenge1-latam/tienda_2.csv"
# url3 = "./base-de-datos-challenge1-latam/tienda_3.csv"
# url4 = "./base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

In [26]:
tienda2.head(15)

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175
5,Guitarra acústica,Instrumentos musicales,298400.0,16100.0,10/09/2021,Beatriz Morales,Leticia,5,Tarjeta de crédito,3,-4.21528,-69.94056
6,Mochila,Deportes y diversión,105900.0,9000.0,10/06/2020,Blanca Ramirez,Bogotá,1,Cupón,1,4.60971,-74.08175
7,Tablet ABXY,Electrónicos,962600.0,49400.0,12/04/2022,Juliana Costa,Medellín,4,Nequi,1,6.25184,-75.56359
8,Olla de presión,Artículos para el hogar,82800.0,4800.0,11/04/2022,Izabela de León,Barranquilla,5,Nequi,1,10.96854,-74.78132
9,Cubo mágico 8x8,Juguetes,9100.0,3800.0,04/09/2021,Camila Rivera,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175
10,Mochila,Deportes y diversión,86800.0,9300.0,18/04/2020,Izabela de León,Medellín,5,Tarjeta de crédito,5,6.25184,-75.56359
11,Secadora de ropa,Electrodomésticos,878900.0,47000.0,25/09/2021,Rafael Acosta,Barranquilla,1,Tarjeta de crédito,2,10.96854,-74.78132
12,Juego de mesa,Juguetes,153000.0,8800.0,13/09/2022,Rafael Acosta,Cúcuta,4,Tarjeta de crédito,10,7.89391,-72.50782
13,Ajedrez de madera,Juguetes,36300.0,2300.0,10/12/2022,Santiago Silva,Medellín,5,Nequi,1,6.25184,-75.56359
14,Bicicleta,Deportes y diversión,513800.0,32000.0,11/11/2021,Juliana Costa,Cali,4,Tarjeta de crédito,2,3.43722,-76.52250

#1. Análisis de facturación

In [23]:
ingresost1=tienda['Precio'].sum()
ingresost2=tienda2['Precio'].sum()
ingresost3=tienda3['Precio'].sum()
ingresost4=tienda4['Precio'].sum()
print(f'ingresos tienda 1: {ingresost1}')
print(f'ingresos tienda 2: {ingresost2}')
print(f'ingresos tienda 3: {ingresost3}')
print(f'ingresos tienda 4: {ingresost4}')
maximo=max(ingresost1,ingresost2,ingresost3,ingresost4)
print(f'La tienda con mayores ingresos es la tienda 1 con {maximo}')

ingresos tienda 1: 1150880400.0
ingresos tienda 2: 1116343500.0
ingresos tienda 3: 1098019600.0
ingresos tienda 4: 1038375700.0
La tienda con mayores ingresos es la tienda 1 con 1150880400.0

# 2. Ventas por categoría

In [28]:
#Contar el número de productos vendidos por tienda por categoria
cantp_VendidosT1 = tienda['Categoría del Producto'].groupby(tienda['Categoría del Producto']).count().sort_values(ascending=False)
cantp_VendidosT2 = tienda['Categoría del Producto'].groupby(tienda2['Categoría del Producto']).count().sort_values(ascending=False)
cantp_VendidosT3 = tienda['Categoría del Producto'].groupby(tienda3['Categoría del Producto']).count().sort_values(ascending=False)
cantp_VendidosT4 = tienda['Categoría del Producto'].groupby(tienda4['Categoría del Producto']).count().sort_values(ascending=False)

print(f'Cantidad de productos vendidos por tienda 1: {cantp_VendidosT1}')
print(f'Cantidad de productos vendidos por tienda 2: {cantp_VendidosT2}')
print(f'Cantidad de productos vendidos por tienda 3: {cantp_VendidosT3}')
print(f'Cantidad de productos vendidos por tienda 4: {cantp_VendidosT4}')

Cantidad de productos vendidos por tienda 1: Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: Categoría del Producto, dtype: int64
Cantidad de productos vendidos por tienda 2: Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: Categoría del Producto, dtype: int64
Cantidad de productos vendidos por tienda 3: Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Artículos para el hogar    177
Instrumentos musicales     177
Name: Categoría del Producto, dtype: int64
Cantidad de productos vendidos por tienda 4: Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: Categoría del Producto, dtype: int64

# 3. Calificación promedio de la tienda

In [29]:
cal_promT1 = tienda['Calificación'].mean()
cal_promT2 = tienda2['Calificación'].mean()
cal_promT3 = tienda3['Calificación'].mean()
cal_promT4 = tienda4['Calificación'].mean()

print(f'Calificación promedio de productos vendidos por tienda 1: {cal_promT1}')
print(f'Calificación promedio de productos vendidos por tienda 2: {cal_promT2}')
print(f'Calificación promedio de productos vendidos por tienda 3: {cal_promT3}')
print(f'Calificación promedio de productos vendidos por tienda 4: {cal_promT4}')

Calificación promedio de productos vendidos por tienda 1: 3.976685036032217
Calificación promedio de productos vendidos por tienda 2: 4.037303942348453
Calificación promedio de productos vendidos por tienda 3: 4.048325561678677
Calificación promedio de productos vendidos por tienda 4: 3.9957591178965224

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda